author = Artur Tarassow
email = atecon@cryptolab.net
version = 1.4
date = 2018-11-14
description = Rolling Time-Series Statistics
tags = C10
min-version = 2018d
data-requirement = needs-time-series-data
gui-main = rolling_ts_gui
label = Rolling Time-series Stats
menu-attachment = MAINWIN/Add
public = rolling_ts rvec2series rolling_ts_gui 
menu-only = rolling_ts_gui 
help = RollingStats_help.txt
sample-script = RollingStats_sample.inp
